// react/TicTacToe/Table.jsx
import React from 'react';
import Tr from './Tr';

const Table = ({ onClick, tableData, dispatch }) => {
  return (
    <table>
      <tbody>
        {Array(tableData.length).fill().map((tr, i) => (<Tr key={i} dispatch={dispatch} rowIndex={i} rowData={tableData[i]} />))}
      </tbody>
    </table>
  );
};

export default Table;

// vue/tic-tac-toe/tic-tac-toe-event-bus/table-component.vue
<template>
  <table>
    <tr-component v-for="(rowData, index) in tableData" :row-data="rowData" :row-index="index" :key="index"></tr-component>
  </table>
</template>

<script>
import TrComponent from './tr-component';

export default {
  components: {
    'tr-component': TrComponent,
  },
  props: {
    tableData: Array,
  },
};
</script>
