// vue/mine-sweeper/table-component.vue
<template>
  <table>
    <tr v-for="(rowData, rowIndex) in tableData" :key="rowIndex">
      <td v-for="(cellData, cellIndex) in rowData" :key="cellIndex">{{ cellData }}</td>
    </tr>    
  </table>
</template>

<script>
import { mapState } from 'vuex';

export default {
  computed: {
    ...mapState(['tableData']),
  }
};
</script>

// react/TicTacToe/table.jsx
import React from 'react';
import Tr from './Tr';

const Table = ({ onClick, tableData, dispatch }) => {
  return (
    <table>
      <tbody>
        {Array(tableData.length).fill().map((tr, i) => (<Tr key={i} dispatch={dispatch} rowIndex={i} rowData={tableData[i]} />))}
      </tbody>
    </table>
  );
};

export default Table;
