// react/ReactRouter/Router.jsx
import React from 'react';
import { BrowserRouter, Route, Link } from 'react-router-dom';

import GameMatcher from './GameMatcher';

const Router = () => {
  return (
    <BrowserRouter>
      <div>
        <div>
          <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
            <Link to="/game/index" className="index">Index</Link>
            <button className="navbar-toggler" type="button" data-toggle="collapse"       data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"       aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <ul className="navbar-nav mr-auto">
                <li className="nav-item mx-3">
                  <Link to="/game/BullsAndCows" className="router-link">Bulls And Cows</Link>
                </li>
                <li className="nav-item mx-3">
                  <Link to="/game/Lotto" className="router-link">Lotto</Link>
                </li>
                <li className="nav-item mx-3">
                  <Link to="/game/ReactionTimeTest" className="router-link">Reaction Time Test</Link>
                </li>
                <li className="nav-item mx-3">
                  <Link to="/game/RockPaperScissors" className="router-link">Rock Paper Scissors</Link>
                </li>
              </ul>
            </div>
          </nav>
        </div>
        <div>
          <Route path="/game/:name" component={GameMatcher} />
        </div>
      </div>
    </BrowserRouter>
  );
};

export default Router;

// vue/vue-router/router.vue
<template>
<div>
  <div>
    <nav class="navbar navbar-expand-lg navbar-white bg-white">
      <a class="navbar-brand" href="#"><router-link to="/game/index">Index</router-link></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item mx-3">
            <a class="nav-link" href="#">
              <router-link to="/game/bulls-and-cows">Bulls And Cows</router-link>
            </a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link" href="#">
              <router-link to="/game/reaction-time-test">Reaction Time Test</router-link>
            </a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link" href="#">
              <router-link to="/game/lotto-generator">Lotto Generator</router-link>
            </a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link" href="#">
              <router-link to="/game/rock-paper-scissors">Rock Paper Scissors</router-link>
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <p>
    <router-view></router-view>
  </p>
</div>
</template>

<script>
import router from './routes';

export default {
  router,
};
</script>

<style>
table {
  border-collapse: collapse;
}
td {
  border: 1px solid black;
  width: 50px;
  height: 50px;
  text-align: center;
  font-size: 30px;
}
#computer {
  width: 142px;
  height: 200px;
  background-position: 0 0;
}
</style>
